"""
Django settings for nutshell project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import dj_database_url
from decouple import Csv, config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Значение по умолчанию работает только локально для разработки.
SECRET_KEY = config(
    'SECRET_KEY',
    default='django-insecure--)(c!n5tfls+8!fe+m3*3r*jy+ixp5(v7uq_)s00p=+r_jz6$u',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

# Локально по умолчанию работают localhost/127.0.0.1.
# На Railway переменная ALLOWED_HOSTS задаётся в окружении и должна
# включать домен вида *.up.railway.app (см. README/инструкцию деплоя).
ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost',
    cast=Csv(),
)

# CORS (опционально)
# В этом проекте django-cors-headers не используется (сайт обслуживает и
# фронтенд, и API из одного и того же Django-приложения, так что
# cross-origin запросов нет). Но если пакет будет добавлен в будущем,
# раскомментируйте 'corsheaders' в INSTALLED_APPS и
# 'corsheaders.middleware.CorsMiddleware' в MIDDLEWARE (первым в списке) —
# CORS_ALLOWED_ORIGINS ниже уже настроен и подхватит переменную окружения.
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://*.up.railway.app',
    cast=Csv(),
)

# Railway работает за прокси и подставляет заголовок X-Forwarded-Proto;
# без этого Django не доверяет CSRF-проверке за HTTPS-прокси.
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='https://*.up.railway.app',
    cast=Csv(),
)


# Application definition

INSTALLED_APPS = [
    'AliceInChains',
    'rest_framework',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'nutshell.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'nutshell.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# На Railway переменная DATABASE_URL подставляется автоматически после
# подключения сервиса PostgreSQL (Add Service -> Database -> PostgreSQL).
# Локально, если DATABASE_URL не задана, используется sqlite3 — это
# позволяет продолжать разработку без поднятия Postgres на своей машине.
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Minsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise отдаёт статику прямо из приложения (без отдельного Nginx) и
# сжимает/кеширует файлы с хешем в имени — это то, что нужно на Railway.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Файлы, загружаемые пользователями / используемые моделями (фото товаров)
# https://docs.djangoproject.com/en/6.0/topics/files/
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR


# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Безопасность в продакшне
# https://docs.djangoproject.com/en/6.0/topics/security/
#
# Когда DEBUG=False (то есть мы в проде, на Railway), включаем secure-флаги
# для cookies, чтобы они передавались только по HTTPS. Локально (DEBUG=True
# по умолчанию) эти флаги не включаются — иначе сайт не будет работать по
# обычному http://127.0.0.1:8000.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Аутентификация
# https://docs.djangoproject.com/en/6.0/topics/auth/default/

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'profile_view'
LOGOUT_REDIRECT_URL = 'index'


# Сообщения (messages framework)
# Приводим тег уровня "error" к классу Bootstrap "danger"
from django.contrib.messages import constants as message_constants

MESSAGE_TAGS = {
    message_constants.ERROR: 'danger',
}


# Настройка отправки email
# https://docs.djangoproject.com/en/6.0/topics/email/
#
# По умолчанию письма не отправляются на реальный почтовый сервер,
# а просто выводятся в консоль, в которой запущен runserver.
# Это удобно для проверки работы checkout без настройки почты.
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'shop@example.com'

# Чтобы отправлять реальные письма (например, через Gmail),
# замените EMAIL_BACKEND на 'django.core.mail.backends.smtp.EmailBackend'
# и заполните параметры ниже:
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your_email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your_app_password'


# Django REST Framework
# https://www.django-rest-framework.org/api-guide/settings/
#
# SessionAuthentication — позволяет ходить в API из браузера, будучи
# залогиненным через обычную форму входа Django (так использует JS на
# страницах сайта — main.js отправляет запросы с тем же сеансом и
# CSRF-токеном).
# BasicAuthentication — позволяет авторизоваться логином/паролем прямо
# в запросе (удобно для проверки через curl/Postman без отдельной формы
# логина).
#
# Глобальный permission по умолчанию — AllowAny: каталог товаров должен
# быть доступен и анонимным пользователям. Эндпоинты с приватными данными
# (корзина, профиль, заказы) и запись в каталог явно требуют
# аутентификации/прав — это указано в permission_classes самих ViewSet'ов
# (см. views.py и permissions.py).
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 9,
}
